# Generated by Django 5.0.4 on 2024-04-26 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KaShea_Tasks', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDo',
            new_name='Tasks',
        ),
    ]
