# Generated by Django 5.0.4 on 2024-04-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('KaShea_Tasks', '0002_rename_todo_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='assigned_to',
            field=models.CharField(blank=True, default='Karissa', max_length=100),
        ),
        migrations.AddField(
            model_name='tasks',
            name='category',
            field=models.CharField(default='General', max_length=100),
        ),
        migrations.AddField(
            model_name='tasks',
            name='priority',
            field=models.CharField(choices=[('High', 'High'), ('Medium', 'Medium'), ('Low', 'Low')], default='Medium', max_length=6),
        ),
        migrations.AddField(
            model_name='tasks',
            name='reminder_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
