# Generated by Django 5.0.4 on 2024-04-26 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(default='', max_length=100)),
                ('file_upload', models.FileField(upload_to='documents/')),
                ('description', models.TextField(default='', max_length=2000)),
                ('upload_date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
