# Generated by Django 5.0.4 on 2024-04-26 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('KaShea_Documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['upload_date']},
        ),
    ]
